'use client'

import { Header } from './header'
import { ColumnSection } from './column-section'

const MOCK_TOKENS = {
  newPairs: [
    {
      id: 'mario',
      name: 'MARIO',
      fullName: 'Official Mario Coin',
      icon: 'M',
      mc: '$192K',
      price: '$9K',
      time: '5s',
      holders: 0,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-blue-500 to-blue-600',
    },
    {
      id: 'game4legs',
      name: 'GAME4LEGS',
      fullName: 'game4legs',
      icon: '🎮',
      mc: '$4.12K',
      price: '$72',
      time: '5s',
      holders: 1,
      transactions: 0,
      visitors: 0,
      lpLocked: 2,
      dayChange: 2,
      hourChange: 1,
      minChange: 2,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-purple-400 to-pink-400',
    },
    {
      id: 'brrs',
      name: 'brrs',
      fullName: 'ugly phnx',
      icon: '🐾',
      mc: '$4.03K',
      price: '$23',
      time: '10s',
      holders: 3,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 1,
      hourChange: 0,
      minChange: 39,
      volume: 1,
      fee: '0.0',
      tx: '1',
      gradient: 'from-amber-300 to-orange-400',
    },
    {
      id: 'grokguys',
      name: 'GrokGuys',
      fullName: 'Just a Grok Guy',
      icon: '🤖',
      mc: '$4K',
      price: '$7',
      time: '20s',
      holders: 1,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 3,
      volume: 0,
      fee: '0.0',
      tx: '2',
      gradient: 'from-green-400 to-emerald-500',
    },
    {
      id: 'jlm',
      name: 'JLM',
      fullName: 'Jesus Language Model',
      icon: '📿',
      mc: '$12.1K',
      price: '$9K',
      time: '34s',
      holders: 39,
      transactions: 37,
      visitors: 2,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-yellow-400 to-orange-500',
    },
  ],
  finalStretch: [
    {
      id: 'velon',
      name: 'VELON',
      fullName: 'Velon',
      icon: '✨',
      mc: '$24.2K',
      price: '$12K',
      time: '7h',
      holders: 0,
      transactions: 0,
      visitors: 1,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-cyan-400 to-blue-500',
    },
    {
      id: 'nvidia',
      name: 'NVIDIA',
      fullName: 'NVIDIA MEME Token',
      icon: '👁️',
      mc: '$48.5K',
      price: '$12K',
      time: '20h',
      holders: 0,
      transactions: 0,
      visitors: 0,
      lpLocked: 5,
      dayChange: 0,
      hourChange: 20,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-lime-300 to-green-500',
    },
    {
      id: 'hoejak',
      name: 'HOEJAK',
      fullName: 'Hoejak',
      icon: '💅',
      mc: '$24.2K',
      price: '$12K',
      time: '10h',
      holders: 2,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 50,
      hourChange: 0,
      minChange: 50,
      volume: 50,
      fee: '0.0',
      tx: '1',
      gradient: 'from-pink-400 to-rose-500',
    },
    {
      id: 'cpt',
      name: 'CPT',
      fullName: 'Empulser Enterprises',
      icon: '🏰',
      mc: '$24.2K',
      price: '$12K',
      time: '14h',
      holders: 2,
      transactions: 0,
      visitors: 32,
      lpLocked: 139,
      dayChange: 50,
      hourChange: 3,
      minChange: 50,
      volume: 29,
      fee: '0.0',
      tx: '2',
      gradient: 'from-slate-400 to-slate-600',
    },
    {
      id: 'kirk',
      name: 'KIRK',
      fullName: 'Official Charlie Kirk Coin',
      icon: '🚀',
      mc: '$24.2K',
      price: '$12K',
      time: '6h',
      holders: 2,
      transactions: 0,
      visitors: 32,
      lpLocked: 134,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-red-400 to-red-600',
    },
  ],
  migrated: [
    {
      id: 'mario-migrated',
      name: 'MARIO',
      fullName: 'Official Mario Coin',
      icon: 'M',
      mc: '$194K',
      price: '$9K',
      time: '4s',
      holders: 6,
      transactions: 0,
      visitors: 0,
      lpLocked: 13,
      dayChange: 96,
      hourChange: 0,
      minChange: 16,
      volume: 0,
      fee: '0.0',
      tx: '13',
      hasBadge: true,
      gradient: 'from-red-500 to-red-600',
    },
    {
      id: 'scrappy',
      name: 'SCRAPPY',
      fullName: 'Arc Raiders Mascot',
      icon: '🦮',
      mc: '$30.8K',
      price: '$15K',
      time: '21s',
      holders: 126,
      transactions: 0,
      visitors: 0,
      lpLocked: 3,
      dayChange: 9,
      hourChange: 50,
      minChange: 50,
      volume: 36,
      fee: '0.0',
      tx: '1',
      gradient: 'from-orange-400 to-amber-500',
    },
    {
      id: 'invest',
      name: 'INVEST',
      fullName: "I'm Telling You Now Is The Time",
      icon: '📈',
      mc: '$28.8K',
      price: '$7K',
      time: '27s',
      holders: 104,
      transactions: 0,
      visitors: 0,
      lpLocked: 1,
      dayChange: 43,
      hourChange: 0,
      minChange: 76,
      volume: 36,
      fee: '0.0',
      tx: '1',
      gradient: 'from-yellow-500 to-amber-600',
    },
    {
      id: 'mayhem',
      name: 'MAYHEM',
      fullName: 'Mayhem Mode',
      icon: '👹',
      mc: '$26.9K',
      price: '$14K',
      time: '35s',
      holders: 197,
      transactions: 0,
      visitors: 35,
      lpLocked: 136,
      dayChange: 5,
      hourChange: 50,
      minChange: 50,
      volume: 0,
      fee: '0.0',
      tx: '61',
      gradient: 'from-yellow-500 to-yellow-600',
    },
    {
      id: 'govslop',
      name: 'Govslop',
      fullName: 'Govslop',
      icon: '🎬',
      mc: '$363K',
      price: '$13K',
      time: '1m',
      holders: 94,
      transactions: 0,
      visitors: 734,
      lpLocked: 809,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-red-500 to-orange-600',
    },
  ],
}

export function PulseInterface() {
  return (
    <div className="min-h-screen bg-[#0a0e27] text-white">
      <Header />
      <div className="flex h-[calc(100vh-140px)]">
        <ColumnSection
          title="New Pairs"
          tokens={MOCK_TOKENS.newPairs}
          category="new-pairs"
        />
        <ColumnSection
          title="Final Stretch"
          tokens={MOCK_TOKENS.finalStretch}
          category="final-stretch"
          isGradientAnimated={true}
        />
        <ColumnSection
          title="Migrated"
          tokens={MOCK_TOKENS.migrated}
          category="migrated"
        />
      </div>
    </div>
  )
}
