'use client'

import { Header } from './header'
import { ColumnSection } from './column-section'
import { BottomBar } from './bottom-bar'

const MOCK_TOKENS = {
  newPairs: [
    {
      id: 'mario',
      name: 'MARIO',
      fullName: 'Official Mario Coin',
      icon: 'M',
      mc: '$192K',
      price: '$9K',
      time: '5s',
      holders: 0,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-blue-500 to-blue-600',
    },
    {
      id: 'game4legs',
      name: 'GAME4LEGS',
      fullName: 'game4legs',
      icon: '🎮',
      mc: '$4.12K',
      price: '$72',
      time: '5s',
      holders: 1,
      transactions: 0,
      visitors: 0,
      lpLocked: 2,
      dayChange: 2,
      hourChange: 1,
      minChange: 2,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-purple-400 to-pink-400',
    },
    {
      id: 'brrs',
      name: 'brrs',
      fullName: 'ugly phnx',
      icon: '🐾',
      mc: '$4.03K',
      price: '$23',
      time: '10s',
      holders: 3,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 1,
      hourChange: 0,
      minChange: 39,
      volume: 1,
      fee: '0.0',
      tx: '1',
      gradient: 'from-amber-300 to-orange-400',
    },
    {
      id: 'grokguys',
      name: 'GrokGuys',
      fullName: 'Just a Grok Guy',
      icon: '🤖',
      mc: '$4K',
      price: '$7',
      time: '20s',
      holders: 1,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 3,
      volume: 0,
      fee: '0.0',
      tx: '2',
      gradient: 'from-green-400 to-emerald-500',
    },
    {
      id: 'jlm',
      name: 'JLM',
      fullName: 'Jesus Language Model',
      icon: '📿',
      mc: '$12.1K',
      price: '$9K',
      time: '34s',
      holders: 39,
      transactions: 37,
      visitors: 2,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-yellow-400 to-orange-500',
    },
    {
      id: 'rrock',
      name: 'RROCK',
      fullName: 'Ron Baron',
      icon: 'R',
      mc: '$3.95K',
      price: '$0',
      time: '0s',
      holders: 1,
      transactions: 4,
      visitors: 0,
      lpLocked: 0,
      dayChange: 18,
      hourChange: 0,
      minChange: 18,
      volume: 0,
      fee: '0.032',
      tx: '2',
      gradient: 'from-blue-500 to-blue-600',
    },
    {
      id: 'lilpepe',
      name: 'LILPEPE',
      fullName: 'LittlePepe',
      icon: '🐸',
      mc: '$5.2K',
      price: '$1.2K',
      time: '1s',
      holders: 2,
      transactions: 8,
      visitors: 1,
      lpLocked: 1,
      dayChange: 25,
      hourChange: 5,
      minChange: 12,
      volume: 2,
      fee: '0.026',
      tx: '4',
      gradient: 'from-green-400 to-emerald-500',
    },
    {
      id: 'ups',
      name: 'UPS',
      fullName: 'United Parcel Service',
      icon: 'U',
      mc: '$8.7K',
      price: '$2.1K',
      time: '12s',
      holders: 4,
      transactions: 12,
      visitors: 3,
      lpLocked: 2,
      dayChange: 8,
      hourChange: 2,
      minChange: 15,
      volume: 5,
      fee: '0.041',
      tx: '6',
      gradient: 'from-yellow-400 to-orange-500',
    },
    {
      id: 'fartrocket',
      name: 'FARTROCKET',
      fullName: 'Fart Rocket',
      icon: '🚀',
      mc: '$15.3K',
      price: '$3.8K',
      time: '8s',
      holders: 6,
      transactions: 15,
      visitors: 5,
      lpLocked: 3,
      dayChange: 32,
      hourChange: 8,
      minChange: 22,
      volume: 8,
      fee: '0.055',
      tx: '9',
      gradient: 'from-red-400 to-red-600',
    },
    {
      id: 'doge2',
      name: 'DOGE2',
      fullName: 'Doge Second',
      icon: '🐕',
      mc: '$22.1K',
      price: '$5.4K',
      time: '15s',
      holders: 9,
      transactions: 21,
      visitors: 7,
      lpLocked: 5,
      dayChange: 45,
      hourChange: 12,
      minChange: 28,
      volume: 12,
      fee: '0.068',
      tx: '14',
      gradient: 'from-cyan-400 to-blue-500',
    },
    {
      id: 'moon',
      name: 'MOON',
      fullName: 'Moon Token',
      icon: '🌙',
      mc: '$18.9K',
      price: '$4.2K',
      time: '22s',
      holders: 7,
      transactions: 18,
      visitors: 4,
      lpLocked: 4,
      dayChange: 28,
      hourChange: 6,
      minChange: 19,
      volume: 9,
      fee: '0.052',
      tx: '11',
      gradient: 'from-purple-400 to-pink-400',
    },
    {
      id: 'star',
      name: 'STAR',
      fullName: 'Star Coin',
      icon: '⭐',
      mc: '$11.5K',
      price: '$2.8K',
      time: '18s',
      holders: 5,
      transactions: 14,
      visitors: 2,
      lpLocked: 2,
      dayChange: 15,
      hourChange: 3,
      minChange: 11,
      volume: 6,
      fee: '0.038',
      tx: '7',
      gradient: 'from-amber-300 to-orange-400',
    },
  ],
  finalStretch: [
    {
      id: 'velon',
      name: 'VELON',
      fullName: 'Velon',
      icon: '✨',
      mc: '$24.2K',
      price: '$12K',
      time: '7h',
      holders: 0,
      transactions: 0,
      visitors: 1,
      lpLocked: 0,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-cyan-400 to-blue-500',
    },
    {
      id: 'nvidia',
      name: 'NVIDIA',
      fullName: 'NVIDIA MEME Token',
      icon: '👁️',
      mc: '$48.5K',
      price: '$12K',
      time: '20h',
      holders: 0,
      transactions: 0,
      visitors: 0,
      lpLocked: 5,
      dayChange: 0,
      hourChange: 20,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-lime-300 to-green-500',
    },
    {
      id: 'hoejak',
      name: 'HOEJAK',
      fullName: 'Hoejak',
      icon: '💅',
      mc: '$24.2K',
      price: '$12K',
      time: '10h',
      holders: 2,
      transactions: 0,
      visitors: 0,
      lpLocked: 0,
      dayChange: 50,
      hourChange: 0,
      minChange: 50,
      volume: 50,
      fee: '0.0',
      tx: '1',
      gradient: 'from-pink-400 to-rose-500',
    },
    {
      id: 'cpt',
      name: 'CPT',
      fullName: 'Empulser Enterprises',
      icon: '🏰',
      mc: '$24.2K',
      price: '$12K',
      time: '14h',
      holders: 2,
      transactions: 0,
      visitors: 32,
      lpLocked: 139,
      dayChange: 50,
      hourChange: 3,
      minChange: 50,
      volume: 29,
      fee: '0.0',
      tx: '2',
      gradient: 'from-slate-400 to-slate-600',
    },
    {
      id: 'kirk',
      name: 'KIRK',
      fullName: 'Official Charlie Kirk Coin',
      icon: '🚀',
      mc: '$24.2K',
      price: '$12K',
      time: '6h',
      holders: 2,
      transactions: 0,
      visitors: 32,
      lpLocked: 134,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-red-400 to-red-600',
    },
    {
      id: 'seahorse2',
      name: 'SEAHORSE2',
      fullName: 'Seahorse Second',
      icon: '🐴',
      mc: '$31.8K',
      price: '$8.5K',
      time: '9h',
      holders: 5,
      transactions: 11,
      visitors: 8,
      lpLocked: 67,
      dayChange: 35,
      hourChange: 7,
      minChange: 24,
      volume: 18,
      fee: '0.048',
      tx: '8',
      gradient: 'from-cyan-400 to-blue-500',
    },
    {
      id: 'uscr',
      name: 'USCR',
      fullName: 'U.S. Crypto Reserve Index',
      icon: '🇺🇸',
      mc: '$42.3K',
      price: '$11.2K',
      time: '12h',
      holders: 8,
      transactions: 19,
      visitors: 12,
      lpLocked: 89,
      dayChange: 22,
      hourChange: 4,
      minChange: 16,
      volume: 14,
      fee: '0.061',
      tx: '13',
      gradient: 'from-lime-300 to-green-500',
    },
    {
      id: 'fight',
      name: 'FIGHT',
      fullName: 'Fight Token',
      icon: '👊',
      mc: '$28.7K',
      price: '$7.3K',
      time: '15h',
      holders: 6,
      transactions: 14,
      visitors: 9,
      lpLocked: 56,
      dayChange: 18,
      hourChange: 3,
      minChange: 12,
      volume: 11,
      fee: '0.044',
      tx: '10',
      gradient: 'from-pink-400 to-rose-500',
    },
    {
      id: 'blob',
      name: 'BLOB',
      fullName: 'Blob Token',
      icon: '🟢',
      mc: '$19.4K',
      price: '$5.1K',
      time: '11h',
      holders: 4,
      transactions: 9,
      visitors: 6,
      lpLocked: 34,
      dayChange: 12,
      hourChange: 2,
      minChange: 8,
      volume: 7,
      fee: '0.035',
      tx: '6',
      gradient: 'from-green-400 to-emerald-500',
    },
    {
      id: 'geometric',
      name: 'GEOMETRIC',
      fullName: 'Geometric Shape',
      icon: '⬟',
      mc: '$35.6K',
      price: '$9.8K',
      time: '18h',
      holders: 7,
      transactions: 16,
      visitors: 11,
      lpLocked: 78,
      dayChange: 28,
      hourChange: 6,
      minChange: 20,
      volume: 15,
      fee: '0.057',
      tx: '12',
      gradient: 'from-slate-400 to-slate-600',
    },
  ],
  migrated: [
    {
      id: 'mario-migrated',
      name: 'MARIO',
      fullName: 'Official Mario Coin',
      icon: 'M',
      mc: '$194K',
      price: '$9K',
      time: '4s',
      holders: 6,
      transactions: 0,
      visitors: 0,
      lpLocked: 13,
      dayChange: 96,
      hourChange: 0,
      minChange: 16,
      volume: 0,
      fee: '0.0',
      tx: '13',
      hasBadge: true,
      gradient: 'from-red-500 to-red-600',
    },
    {
      id: 'scrappy',
      name: 'SCRAPPY',
      fullName: 'Arc Raiders Mascot',
      icon: '🦮',
      mc: '$30.8K',
      price: '$15K',
      time: '21s',
      holders: 126,
      transactions: 0,
      visitors: 0,
      lpLocked: 3,
      dayChange: 9,
      hourChange: 50,
      minChange: 50,
      volume: 36,
      fee: '0.0',
      tx: '1',
      gradient: 'from-orange-400 to-amber-500',
    },
    {
      id: 'invest',
      name: 'INVEST',
      fullName: "I'm Telling You Now Is The Time",
      icon: '📈',
      mc: '$28.8K',
      price: '$7K',
      time: '27s',
      holders: 104,
      transactions: 0,
      visitors: 0,
      lpLocked: 1,
      dayChange: 43,
      hourChange: 0,
      minChange: 76,
      volume: 36,
      fee: '0.0',
      tx: '1',
      gradient: 'from-yellow-500 to-amber-600',
    },
    {
      id: 'mayhem',
      name: 'MAYHEM',
      fullName: 'Mayhem Mode',
      icon: '👹',
      mc: '$26.9K',
      price: '$14K',
      time: '35s',
      holders: 197,
      transactions: 0,
      visitors: 35,
      lpLocked: 136,
      dayChange: 5,
      hourChange: 50,
      minChange: 50,
      volume: 0,
      fee: '0.0',
      tx: '61',
      gradient: 'from-yellow-500 to-yellow-600',
    },
    {
      id: 'govslop',
      name: 'Govslop',
      fullName: 'Govslop',
      icon: '🎬',
      mc: '$363K',
      price: '$13K',
      time: '1m',
      holders: 94,
      transactions: 0,
      visitors: 734,
      lpLocked: 809,
      dayChange: 0,
      hourChange: 0,
      minChange: 0,
      volume: 0,
      fee: '0.0',
      tx: '1',
      gradient: 'from-red-500 to-orange-600',
    },
    {
      id: 'ups-migrated',
      name: 'UPS',
      fullName: 'United Parcel Service',
      icon: '📦',
      mc: '$52.4K',
      price: '$12.8K',
      time: '2m',
      holders: 156,
      transactions: 45,
      visitors: 89,
      lpLocked: 234,
      dayChange: 67,
      hourChange: 15,
      minChange: 34,
      volume: 42,
      fee: '0.072',
      tx: '28',
      hasBadge: true,
      gradient: 'from-blue-500 to-blue-600',
    },
    {
      id: 'elord',
      name: 'E',
      fullName: 'Lord Marquaad E',
      icon: 'E',
      mc: '$78.9K',
      price: '$18.5K',
      time: '3m',
      holders: 203,
      transactions: 67,
      visitors: 124,
      lpLocked: 456,
      dayChange: 89,
      hourChange: 22,
      minChange: 48,
      volume: 58,
      fee: '0.089',
      tx: '35',
      hasBadge: true,
      gradient: 'from-purple-400 to-pink-400',
    },
    {
      id: 'hakimi',
      name: 'HAKIMI',
      fullName: 'Hakimi Hakimi',
      icon: '🐱',
      mc: '$45.2K',
      price: '$11.3K',
      time: '1m',
      holders: 178,
      transactions: 52,
      visitors: 98,
      lpLocked: 312,
      dayChange: 54,
      hourChange: 12,
      minChange: 29,
      volume: 37,
      fee: '0.063',
      tx: '24',
      hasBadge: true,
      gradient: 'from-amber-300 to-orange-400',
    },
    {
      id: 'cr5',
      name: 'CR5',
      fullName: 'CR5 Token',
      icon: '👤',
      mc: '$67.8K',
      price: '$16.2K',
      time: '4m',
      holders: 245,
      transactions: 78,
      visitors: 156,
      lpLocked: 567,
      dayChange: 72,
      hourChange: 18,
      minChange: 41,
      volume: 64,
      fee: '0.095',
      tx: '42',
      hasBadge: true,
      gradient: 'from-green-400 to-emerald-500',
    },
    {
      id: 'prizepicks',
      name: 'PRIZEPICKS',
      fullName: 'Picks PrizePicks Official',
      icon: '🎯',
      mc: '$91.3K',
      price: '$22.7K',
      time: '5m',
      holders: 312,
      transactions: 94,
      visitors: 201,
      lpLocked: 789,
      dayChange: 95,
      hourChange: 25,
      minChange: 56,
      volume: 81,
      fee: '0.112',
      tx: '58',
      hasBadge: true,
      gradient: 'from-cyan-400 to-blue-500',
    },
    {
      id: 'wifejak',
      name: 'WIFEJAK',
      fullName: 'Wifejak Token',
      icon: '👩',
      mc: '$38.6K',
      price: '$9.4K',
      time: '2m',
      holders: 134,
      transactions: 38,
      visitors: 67,
      lpLocked: 198,
      dayChange: 41,
      hourChange: 9,
      minChange: 23,
      volume: 28,
      fee: '0.051',
      tx: '19',
      hasBadge: true,
      gradient: 'from-pink-400 to-rose-500',
    },
    {
      id: 'nvidia-migrated',
      name: 'NVIDIA',
      fullName: 'NVIDIA Token',
      icon: '💻',
      mc: '$124.7K',
      price: '$31.2K',
      time: '6m',
      holders: 389,
      transactions: 112,
      visitors: 267,
      lpLocked: 923,
      dayChange: 108,
      hourChange: 31,
      minChange: 67,
      volume: 95,
      fee: '0.134',
      tx: '71',
      hasBadge: true,
      gradient: 'from-lime-300 to-green-500',
    },
  ],
}

export function PulseInterface() {
  return (
    <div className="h-screen bg-[#000000] text-white flex flex-col overflow-hidden">
      <Header />
      <div className="px-[0.5cm] py-[0.5cm] flex-1 overflow-hidden min-h-0">
        <div className="w-full h-full bg-[#050810] rounded-lg border border-[#1a1f3a] overflow-hidden flex flex-col">
          <div className="flex flex-1 overflow-hidden min-h-0">
            <ColumnSection
              title="New Pairs"
              tokens={MOCK_TOKENS.newPairs}
              category="new-pairs"
            />
            <ColumnSection
              title="Final Stretch"
              tokens={MOCK_TOKENS.finalStretch}
              category="final-stretch"
              isGradientAnimated={true}
            />
            <ColumnSection
              title="Migrated"
              tokens={MOCK_TOKENS.migrated}
              category="migrated"
            />
          </div>
        </div>
      </div>
      <div className="flex-shrink-0">
        <BottomBar />
      </div>
    </div>
  )
}
